-- Databricks notebook source
-- MAGIC %md
-- MAGIC # IPL cricket analysis 2008-2024 - SQL pipeline (Databricks SQL)
-- MAGIC Generated by `scripts/build_databricks.py` from `sql/`. Executed on a serverless SQL warehouse.
-- MAGIC
-- MAGIC 1. Upload the full raw files to the Unity Catalog volume `/Volumes/workspace/da_learn_13/raw` (see `databricks/SETUP.md`).
-- MAGIC 2. Attach to a SQL warehouse (or DBR 13.3+) and *Run all*.
-- MAGIC 3. Cells: config -> 01 staging (`read_files`) -> 02 cleaning -> 03 star schema -> 04 KPIs -> 05 data quality -> visual queries.

-- COMMAND ----------

-- Config
CREATE SCHEMA IF NOT EXISTS workspace.da_learn_13;
CREATE VOLUME IF NOT EXISTS workspace.da_learn_13.raw;
USE CATALOG workspace;
USE SCHEMA da_learn_13;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 01 Staging (raw landing, no type inference for CSV; casting happens in 02)

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_matches AS
SELECT * EXCEPT (_rescued_data)
FROM read_files('/Volumes/workspace/da_learn_13/raw/matches_2008-2024.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false);

-- COMMAND ----------

CREATE OR REPLACE TABLE stg_deliveries AS
SELECT *
FROM read_files('/Volumes/workspace/da_learn_13/raw/deliveries_2008-2024.csv',
  format => 'csv', header => true, multiLine => true, escape => '"', inferColumnTypes => false,
  schema => 'match_id STRING, inning STRING, batting_team STRING, bowling_team STRING, over_no STRING, ball_no STRING, batter STRING, bowler STRING, non_striker STRING, batsman_runs STRING, extra_runs STRING, total_runs STRING, extras_type STRING, is_wicket STRING, player_dismissed STRING, dismissal_kind STRING, fielder STRING');

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 02 Cleaning (`sql/02_cleaning.sql`)

-- COMMAND ----------

-- 02_cleaning.sql  (Spark SQL dialect; DuckDB via 00 shims)

CREATE OR REPLACE TABLE map_team AS
SELECT * FROM (VALUES
  ('Delhi Daredevils', 'Delhi Capitals'),
  ('Kings XI Punjab', 'Punjab Kings'),
  ('Royal Challengers Bangalore', 'Royal Challengers Bengaluru'),
  ('Rising Pune Supergiants', 'Rising Pune Supergiant')
) AS t(raw_name, team_name);

-- COMMAND ----------

-- canonical venue: text before the first comma, dots removed, historical names mapped to current

CREATE OR REPLACE TABLE cln_matches AS
WITH typed AS (
  SELECT
    TRY_CAST(trim(id) AS BIGINT)                                   AS match_id,
    TRY_CAST(substr(trim(season), 1, 4) AS INT)                    AS season,
    to_date(trim(date))                                          AS match_date,
    NULLIF(NULLIF(trim(city), 'NA'), '')                           AS city_raw,
    trim(venue)                                                    AS venue_raw,
    trim(match_type)                                               AS match_type,
    NULLIF(NULLIF(trim(player_of_match), 'NA'), '')                AS player_of_match,
    trim(team1) AS team1_raw, trim(team2) AS team2_raw,
    trim(toss_winner) AS toss_winner_raw,
    lower(trim(toss_decision))                                     AS toss_decision,
    NULLIF(NULLIF(trim(winner), 'NA'), '')                         AS winner_raw,
    lower(trim(result))                                            AS result,
    TRY_CAST(NULLIF(trim(result_margin), 'NA') AS INT)             AS result_margin,
    TRY_CAST(NULLIF(trim(target_runs), 'NA') AS INT)               AS target_runs,
    TRY_CAST(NULLIF(trim(target_overs), 'NA') AS DOUBLE)           AS target_overs,
    CASE WHEN upper(trim(super_over)) = 'Y' THEN 1 ELSE 0 END      AS super_over_flag,
    CASE WHEN trim(method) = 'D/L' THEN 1 ELSE 0 END               AS dl_method_flag
  FROM stg_matches
), venue_std AS (
  SELECT *,
    trim(replace(replace(split_part(venue_raw, ',', 1), '.', ' '), '  ', ' ')) AS v0
  FROM typed
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY match_id ORDER BY match_date) AS rn FROM venue_std WHERE match_id IS NOT NULL
)
SELECT
  r.match_id, r.season, r.match_date, r.match_type,
  CASE WHEN r.match_type = 'League' THEN 'League' ELSE 'Playoff' END                     AS stage,
  CASE r.v0
    WHEN 'Feroz Shah Kotla' THEN 'Arun Jaitley Stadium'
    WHEN 'Punjab Cricket Association Stadium' THEN 'Punjab Cricket Association IS Bindra Stadium'
    WHEN 'Sardar Patel Stadium' THEN 'Narendra Modi Stadium'
    WHEN 'Sheikh Zayed Stadium' THEN 'Zayed Cricket Stadium'
    WHEN 'Subrata Roy Sahara Stadium' THEN 'Maharashtra Cricket Association Stadium'
    ELSE r.v0 END                                                                        AS venue,
  r.venue_raw,
  CASE WHEN r.city_raw = 'Bangalore' THEN 'Bengaluru'
       WHEN r.city_raw IS NOT NULL THEN r.city_raw
       WHEN r.venue_raw LIKE '%Dubai%' THEN 'Dubai'
       WHEN r.venue_raw LIKE '%Sharjah%' THEN 'Sharjah'
       ELSE NULL END                                                                     AS city,
  COALESCE(t1.team_name, r.team1_raw)  AS team1,
  COALESCE(t2.team_name, r.team2_raw)  AS team2,
  COALESCE(tw.team_name, r.toss_winner_raw) AS toss_winner,
  r.toss_decision,
  COALESCE(w.team_name, r.winner_raw)  AS winner,
  r.result, r.result_margin, r.target_runs, r.target_overs, r.super_over_flag, r.dl_method_flag,
  r.player_of_match,
  CASE WHEN r.toss_decision = 'bat' THEN COALESCE(tw.team_name, r.toss_winner_raw)
       WHEN COALESCE(tw.team_name, r.toss_winner_raw) = COALESCE(t1.team_name, r.team1_raw) THEN COALESCE(t2.team_name, r.team2_raw)
       ELSE COALESCE(t1.team_name, r.team1_raw) END                                      AS bat_first_team,
  CASE WHEN r.winner_raw IS NULL THEN 1 ELSE 0 END                                       AS no_result_flag,
  CASE WHEN r.winner_raw IS NOT NULL AND r.winner_raw = r.toss_winner_raw THEN 1 ELSE 0 END AS toss_winner_won_flag,
  CASE WHEN r.venue_raw <> r.v0 THEN 1 ELSE 0 END                                        AS dq_venue_renamed
FROM ranked r
LEFT JOIN map_team t1 ON r.team1_raw = t1.raw_name
LEFT JOIN map_team t2 ON r.team2_raw = t2.raw_name
LEFT JOIN map_team tw ON r.toss_winner_raw = tw.raw_name
LEFT JOIN map_team w  ON r.winner_raw = w.raw_name
WHERE r.rn = 1 AND r.season IS NOT NULL AND r.match_date IS NOT NULL
  AND r.toss_decision IN ('bat', 'field');

-- COMMAND ----------

CREATE OR REPLACE TABLE cln_deliveries AS
WITH typed AS (
  SELECT
    TRY_CAST(trim(match_id) AS BIGINT)                AS match_id,
    TRY_CAST(trim(inning) AS INT)                     AS inning,
    trim(batting_team)                                AS batting_team_raw,
    trim(bowling_team)                                AS bowling_team_raw,
    TRY_CAST(trim(over_no) AS INT)                    AS over_no,
    TRY_CAST(trim(ball_no) AS INT)                    AS ball_no,
    trim(batter) AS batter, trim(bowler) AS bowler, trim(non_striker) AS non_striker,
    TRY_CAST(trim(batsman_runs) AS INT)               AS batsman_runs,
    TRY_CAST(trim(extra_runs) AS INT)                 AS extra_runs,
    TRY_CAST(trim(total_runs) AS INT)                 AS total_runs,
    NULLIF(NULLIF(lower(trim(extras_type)), 'na'), '') AS extras_type,
    TRY_CAST(trim(is_wicket) AS INT)                  AS is_wicket,
    NULLIF(NULLIF(trim(player_dismissed), 'NA'), '')  AS player_dismissed,
    NULLIF(NULLIF(lower(trim(dismissal_kind)), 'na'), '') AS dismissal_kind,
    NULLIF(NULLIF(trim(fielder), 'NA'), '')           AS fielder
  FROM stg_deliveries
), ranked AS (
  SELECT *, ROW_NUMBER() OVER (PARTITION BY match_id, inning, over_no, ball_no ORDER BY total_runs DESC) AS rn
  FROM typed
)
SELECT
  d.match_id, d.inning, d.over_no, d.ball_no,
  COALESCE(bt.team_name, d.batting_team_raw) AS batting_team,
  COALESCE(bw.team_name, d.bowling_team_raw) AS bowling_team,
  d.batter, d.bowler, d.non_striker,
  d.batsman_runs, d.extra_runs, d.total_runs, d.extras_type, d.is_wicket,
  d.player_dismissed, d.dismissal_kind, d.fielder,
  CASE WHEN d.inning > 2 THEN 1 ELSE 0 END                                         AS super_over_flag,
  CASE WHEN COALESCE(d.extras_type, '') = 'wides' THEN 0 ELSE 1 END                AS ball_faced_flag,
  CASE WHEN COALESCE(d.extras_type, '') IN ('wides', 'noballs') THEN 0 ELSE 1 END  AS legal_ball_flag,
  d.total_runs - CASE WHEN COALESCE(d.extras_type, '') IN ('byes', 'legbyes', 'penalty') THEN d.extra_runs ELSE 0 END AS bowler_runs,
  CASE WHEN d.dismissal_kind IN ('bowled', 'caught', 'lbw', 'stumped', 'caught and bowled', 'hit wicket') THEN 1 ELSE 0 END AS bowler_wicket_flag,
  CASE WHEN d.batsman_runs = 4 THEN 1 ELSE 0 END AS four_flag,
  CASE WHEN d.batsman_runs = 6 THEN 1 ELSE 0 END AS six_flag,
  CASE WHEN d.over_no < 6 THEN '1 Powerplay (1-6)' WHEN d.over_no < 15 THEN '2 Middle (7-15)' ELSE '3 Death (16-20)' END AS phase,
  CASE WHEN d.total_runs > 7 OR d.batsman_runs NOT IN (0, 1, 2, 3, 4, 5, 6) THEN 1 ELSE 0 END AS dq_runs_outlier,
  CASE WHEN d.batsman_runs + d.extra_runs <> d.total_runs THEN 1 ELSE 0 END AS dq_runs_mismatch
FROM ranked d
LEFT JOIN map_team bt ON d.batting_team_raw = bt.raw_name
LEFT JOIN map_team bw ON d.bowling_team_raw = bw.raw_name
WHERE d.rn = 1 AND d.match_id IS NOT NULL AND d.inning IS NOT NULL AND d.over_no BETWEEN 0 AND 19
  AND d.total_runs IS NOT NULL
  AND d.match_id IN (SELECT match_id FROM cln_matches);

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 03 Star schema (`sql/03_model.sql`)

-- COMMAND ----------

-- 03_model.sql  Star schema: fact_deliveries (ball grain) + fact_matches (match grain)

CREATE OR REPLACE TABLE dim_team AS
SELECT ROW_NUMBER() OVER (ORDER BY team_name) AS team_key, team_name,
       CASE WHEN team_name IN ('Chennai Super Kings', 'Delhi Capitals', 'Gujarat Titans', 'Kolkata Knight Riders',
            'Lucknow Super Giants', 'Mumbai Indians', 'Punjab Kings', 'Rajasthan Royals',
            'Royal Challengers Bengaluru', 'Sunrisers Hyderabad') THEN 1 ELSE 0 END AS is_active_2024
FROM (SELECT team1 AS team_name FROM cln_matches UNION SELECT team2 FROM cln_matches) t;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_venue AS
SELECT ROW_NUMBER() OVER (ORDER BY venue) AS venue_key, venue, city, country
FROM (
  SELECT venue, MAX(city) AS city,
         CASE WHEN MAX(city) IN ('Dubai', 'Sharjah', 'Abu Dhabi') THEN 'UAE'
              WHEN MAX(city) IN ('Cape Town', 'Port Elizabeth', 'Durban', 'Centurion', 'Johannesburg', 'Kimberley', 'Bloemfontein', 'East London') THEN 'South Africa'
              ELSE 'India' END AS country
  FROM cln_matches GROUP BY venue
) v;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_player AS
SELECT ROW_NUMBER() OVER (ORDER BY player_name) AS player_key, player_name
FROM (SELECT batter AS player_name FROM cln_deliveries UNION SELECT bowler FROM cln_deliveries
      UNION SELECT non_striker FROM cln_deliveries) p;

-- COMMAND ----------

CREATE OR REPLACE TABLE dim_season AS
SELECT season, MIN(match_date) AS first_match, MAX(match_date) AS last_match, COUNT(*) AS matches,
       MAX(CASE WHEN match_type = 'Final' THEN winner END) AS champion
FROM cln_matches GROUP BY season;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_matches AS
SELECT m.match_id, m.season, m.match_date, m.stage, m.match_type, v.venue_key,
       t1.team_key AS team1_key, t2.team_key AS team2_key, tw.team_key AS toss_winner_key,
       w.team_key AS winner_key, bf.team_key AS bat_first_team_key,
       m.toss_decision, m.result, m.result_margin, m.target_runs, m.super_over_flag, m.dl_method_flag,
       m.no_result_flag, m.toss_winner_won_flag,
       CASE WHEN m.no_result_flag = 0 AND m.winner = m.bat_first_team THEN 1 ELSE 0 END AS bat_first_won_flag,
       s1.runs AS first_innings_runs, s1.wkts AS first_innings_wkts,
       s2.runs AS second_innings_runs, s2.wkts AS second_innings_wkts
FROM cln_matches m
JOIN dim_venue v ON m.venue = v.venue
JOIN dim_team t1 ON m.team1 = t1.team_name
JOIN dim_team t2 ON m.team2 = t2.team_name
JOIN dim_team tw ON m.toss_winner = tw.team_name
LEFT JOIN dim_team w ON m.winner = w.team_name
LEFT JOIN dim_team bf ON m.bat_first_team = bf.team_name
LEFT JOIN (SELECT match_id, SUM(total_runs) AS runs, SUM(is_wicket) AS wkts FROM cln_deliveries WHERE inning = 1 GROUP BY match_id) s1 ON m.match_id = s1.match_id
LEFT JOIN (SELECT match_id, SUM(total_runs) AS runs, SUM(is_wicket) AS wkts FROM cln_deliveries WHERE inning = 2 GROUP BY match_id) s2 ON m.match_id = s2.match_id;

-- COMMAND ----------

CREATE OR REPLACE TABLE fact_deliveries AS
SELECT d.match_id, d.inning, d.over_no, d.ball_no, m.season,
       bt.team_key AS batting_team_key, bw.team_key AS bowling_team_key,
       pb.player_key AS batter_key, pw.player_key AS bowler_key,
       d.batsman_runs, d.extra_runs, d.total_runs, d.bowler_runs, d.extras_type, d.is_wicket, d.dismissal_kind,
       d.bowler_wicket_flag, d.ball_faced_flag, d.legal_ball_flag, d.four_flag, d.six_flag, d.phase, d.super_over_flag
FROM cln_deliveries d
JOIN cln_matches m ON d.match_id = m.match_id
JOIN dim_team bt ON d.batting_team = bt.team_name
JOIN dim_team bw ON d.bowling_team = bw.team_name
JOIN dim_player pb ON d.batter = pb.player_name
JOIN dim_player pw ON d.bowler = pw.player_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 04 Business KPIs (`sql/04_analysis.sql`)

-- COMMAND ----------

-- 04_analysis.sql  KPI + business-question tables (a_*). Super overs (inning > 2) excluded from player stats.

CREATE OR REPLACE TABLE a_kpi_headline AS
SELECT
  (SELECT COUNT(*) FROM fact_matches)                                         AS matches,
  (SELECT COUNT(*) FROM fact_deliveries)                                      AS deliveries,
  (SELECT COUNT(DISTINCT season) FROM fact_matches)                           AS seasons,
  (SELECT COUNT(*) FROM dim_team)                                             AS teams,
  (SELECT COUNT(*) FROM dim_venue)                                            AS venues,
  (SELECT COUNT(*) FROM dim_player)                                           AS players,
  (SELECT SUM(total_runs) FROM fact_deliveries WHERE super_over_flag = 0)     AS total_runs,
  (SELECT SUM(is_wicket) FROM fact_deliveries WHERE super_over_flag = 0)      AS total_wickets,
  (SELECT SUM(six_flag) FROM fact_deliveries WHERE super_over_flag = 0)       AS total_sixes,
  (SELECT ROUND(AVG(first_innings_runs), 1) FROM fact_matches WHERE dl_method_flag = 0 AND no_result_flag = 0) AS avg_first_innings_score,
  (SELECT ROUND(6.0 * SUM(total_runs) / SUM(legal_ball_flag), 2) FROM fact_deliveries WHERE super_over_flag = 0) AS run_rate,
  (SELECT ROUND(100.0 * SUM(toss_winner_won_flag) / COUNT(*), 2) FROM fact_matches WHERE no_result_flag = 0) AS toss_winner_win_pct,
  (SELECT ROUND(100.0 * SUM(bat_first_won_flag) / COUNT(*), 2) FROM fact_matches WHERE no_result_flag = 0) AS bat_first_win_pct,
  (SELECT ROUND(100.0 * SUM(CASE WHEN toss_decision = 'field' THEN 1 ELSE 0 END) / COUNT(*), 2) FROM fact_matches) AS toss_field_choice_pct;

-- COMMAND ----------

-- Q1 team win rates (current franchise names; no-results excluded; tie decided by super over counts for winner)

CREATE OR REPLACE TABLE a_team_win_rates AS
WITH g AS (
  SELECT team1_key AS team_key, winner_key, no_result_flag, stage FROM fact_matches
  UNION ALL SELECT team2_key, winner_key, no_result_flag, stage FROM fact_matches
)
SELECT t.team_name, COUNT(*) AS matches, SUM(CASE WHEN g.winner_key = g.team_key THEN 1 ELSE 0 END) AS wins,
       SUM(g.no_result_flag) AS no_results,
       ROUND(100.0 * SUM(CASE WHEN g.winner_key = g.team_key THEN 1 ELSE 0 END) / NULLIF(SUM(1 - g.no_result_flag), 0), 2) AS win_pct,
       COALESCE(MAX(c.titles), 0) AS titles
FROM g JOIN dim_team t ON g.team_key = t.team_key
LEFT JOIN (SELECT champion, COUNT(*) AS titles FROM dim_season GROUP BY champion) c ON c.champion = t.team_name
GROUP BY t.team_name;

-- COMMAND ----------

-- Q2 toss impact by decision and by season

CREATE OR REPLACE TABLE a_toss_impact AS
SELECT toss_decision, COUNT(*) AS matches, SUM(toss_winner_won_flag) AS toss_winner_won,
       ROUND(100.0 * SUM(toss_winner_won_flag) / COUNT(*), 2) AS toss_winner_win_pct,
       ROUND(100.0 * SUM(bat_first_won_flag) / COUNT(*), 2) AS bat_first_win_pct
FROM fact_matches WHERE no_result_flag = 0 GROUP BY toss_decision;

-- COMMAND ----------

CREATE OR REPLACE TABLE a_season_trend AS
SELECT f.season, COUNT(*) AS matches,
       ROUND(100.0 * SUM(CASE WHEN toss_decision = 'field' THEN 1 ELSE 0 END) / COUNT(*), 1) AS toss_field_choice_pct,
       ROUND(100.0 * SUM(toss_winner_won_flag) / NULLIF(SUM(1 - no_result_flag), 0), 1) AS toss_winner_win_pct,
       ROUND(100.0 * SUM(bat_first_won_flag) / NULLIF(SUM(1 - no_result_flag), 0), 1) AS bat_first_win_pct,
       ROUND(AVG(CASE WHEN dl_method_flag = 0 THEN first_innings_runs END), 1) AS avg_first_innings_score,
       MAX(s.champion) AS champion
FROM fact_matches f JOIN dim_season s ON f.season = s.season
GROUP BY f.season;

-- COMMAND ----------

-- Q3 top batters (all seasons)

CREATE OR REPLACE TABLE a_top_batters AS
WITH inn AS (
  SELECT batter_key, match_id, inning, SUM(batsman_runs) AS r FROM fact_deliveries WHERE super_over_flag = 0 GROUP BY 1, 2, 3
), ms AS (
  SELECT batter_key, COUNT(*) AS innings, SUM(CASE WHEN r BETWEEN 50 AND 99 THEN 1 ELSE 0 END) AS fifties,
         SUM(CASE WHEN r >= 100 THEN 1 ELSE 0 END) AS hundreds, MAX(r) AS high_score
  FROM inn GROUP BY batter_key
), outs AS (
  SELECT p.player_key, COUNT(*) AS dismissals
  FROM cln_deliveries d JOIN dim_player p ON d.player_dismissed = p.player_name
  WHERE d.super_over_flag = 0 AND d.dismissal_kind <> 'retired hurt' GROUP BY p.player_key
), b AS (
  SELECT batter_key, SUM(batsman_runs) AS runs, SUM(ball_faced_flag) AS balls_faced, SUM(four_flag) AS fours, SUM(six_flag) AS sixes
  FROM fact_deliveries WHERE super_over_flag = 0 GROUP BY batter_key
)
SELECT p.player_name AS batter, ms.innings, b.runs, b.balls_faced,
       ROUND(100.0 * b.runs / NULLIF(b.balls_faced, 0), 2) AS strike_rate,
       ROUND(1.0 * b.runs / NULLIF(o.dismissals, 0), 2)  AS batting_avg,
       b.fours, b.sixes, ms.fifties, ms.hundreds, ms.high_score
FROM b
JOIN ms ON b.batter_key = ms.batter_key
JOIN dim_player p ON b.batter_key = p.player_key
LEFT JOIN outs o ON b.batter_key = o.player_key
WHERE b.runs >= 1500;

-- COMMAND ----------

-- Q4 top bowlers (wickets credited to bowler; byes / leg-byes not charged)

CREATE OR REPLACE TABLE a_top_bowlers AS
SELECT p.player_name AS bowler, COUNT(DISTINCT f.match_id) AS matches, SUM(f.bowler_wicket_flag) AS wickets,
       SUM(f.legal_ball_flag) AS legal_balls, SUM(f.bowler_runs) AS runs_conceded,
       ROUND(6.0 * SUM(f.bowler_runs) / NULLIF(SUM(f.legal_ball_flag), 0), 2) AS economy,
       ROUND(1.0 * SUM(f.bowler_runs) / NULLIF(SUM(f.bowler_wicket_flag), 0), 2) AS bowling_avg,
       ROUND(1.0 * SUM(f.legal_ball_flag) / NULLIF(SUM(f.bowler_wicket_flag), 0), 2) AS strike_rate
FROM fact_deliveries f JOIN dim_player p ON f.bowler_key = p.player_key
WHERE f.super_over_flag = 0
GROUP BY p.player_name
HAVING SUM(f.bowler_wicket_flag) >= 75;

-- COMMAND ----------

-- Q5 venue effects (venues with >= 20 completed matches)

CREATE OR REPLACE TABLE a_venue_effects AS
SELECT v.venue, v.city, v.country, COUNT(*) AS matches,
       ROUND(AVG(CASE WHEN f.dl_method_flag = 0 THEN f.first_innings_runs END), 1) AS avg_first_innings_score,
       ROUND(100.0 * SUM(f.bat_first_won_flag) / COUNT(*), 1) AS bat_first_win_pct,
       ROUND(100.0 * SUM(f.toss_winner_won_flag) / COUNT(*), 1) AS toss_winner_win_pct,
       ROUND(100.0 * SUM(CASE WHEN f.toss_decision = 'field' THEN 1 ELSE 0 END) / COUNT(*), 1) AS toss_field_choice_pct
FROM fact_matches f JOIN dim_venue v ON f.venue_key = v.venue_key
WHERE f.no_result_flag = 0
GROUP BY v.venue, v.city, v.country
HAVING COUNT(*) >= 20;

-- COMMAND ----------

-- Q6 scoring by phase of innings

CREATE OR REPLACE TABLE a_phase_scoring AS
SELECT phase, SUM(legal_ball_flag) AS legal_balls, SUM(total_runs) AS runs,
       ROUND(6.0 * SUM(total_runs) / SUM(legal_ball_flag), 2) AS run_rate,
       ROUND(100.0 * SUM(is_wicket) / SUM(legal_ball_flag), 2) AS wicket_pct_per_ball,
       ROUND(100.0 * SUM(four_flag + six_flag) / SUM(legal_ball_flag), 2) AS boundary_pct_per_ball
FROM fact_deliveries WHERE super_over_flag = 0 AND inning <= 2
GROUP BY phase;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## 05 Data-quality checks (`sql/05_quality_checks.sql`)

-- COMMAND ----------

-- 05_quality_checks.sql  before/after counts, DQ issue counts and hard assertions

CREATE OR REPLACE TABLE dq_row_counts AS
SELECT 'matches' AS entity, (SELECT COUNT(*) FROM stg_matches) AS raw_rows,
       (SELECT COUNT(DISTINCT trim(id)) FROM stg_matches) AS distinct_keys, (SELECT COUNT(*) FROM cln_matches) AS clean_rows, 'match_id' AS grain
UNION ALL SELECT 'deliveries', (SELECT COUNT(*) FROM stg_deliveries),
       (SELECT COUNT(*) FROM (SELECT DISTINCT trim(match_id), trim(inning), trim(over_no), trim(ball_no) FROM stg_deliveries) x),
       (SELECT COUNT(*) FROM cln_deliveries), 'match_id + inning + over + ball'
UNION ALL SELECT 'fact_matches', NULL, NULL, (SELECT COUNT(*) FROM fact_matches), 'match'
UNION ALL SELECT 'fact_deliveries', NULL, NULL, (SELECT COUNT(*) FROM fact_deliveries), 'ball'
UNION ALL SELECT 'dim_team', NULL, NULL, (SELECT COUNT(*) FROM dim_team), 'franchise (current name)'
UNION ALL SELECT 'dim_venue', NULL, NULL, (SELECT COUNT(*) FROM dim_venue), 'canonical venue'
UNION ALL SELECT 'dim_player', NULL, NULL, (SELECT COUNT(*) FROM dim_player), 'player name'
UNION ALL SELECT 'dim_season', NULL, NULL, (SELECT COUNT(*) FROM dim_season), 'season';

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_issues AS
SELECT 'matches: distinct raw venue strings' AS check_name, (SELECT COUNT(DISTINCT trim(venue)) FROM stg_matches) AS affected_rows
UNION ALL SELECT 'matches: canonical venues after standardisation', (SELECT COUNT(*) FROM dim_venue)
UNION ALL SELECT 'matches: raw team names', (SELECT COUNT(*) FROM (SELECT trim(team1) t FROM stg_matches UNION SELECT trim(team2) FROM stg_matches) x)
UNION ALL SELECT 'matches: franchises after rename mapping', (SELECT COUNT(*) FROM dim_team)
UNION ALL SELECT 'matches: city NA (filled from venue)', (SELECT COUNT(*) FROM stg_matches WHERE trim(city) = 'NA')
UNION ALL SELECT 'matches: no result (winner NA)', (SELECT SUM(no_result_flag) FROM cln_matches)
UNION ALL SELECT 'matches: tie decided by super over', (SELECT SUM(super_over_flag) FROM cln_matches)
UNION ALL SELECT 'matches: D/L method', (SELECT SUM(dl_method_flag) FROM cln_matches)
UNION ALL SELECT 'deliveries: header + values space-padded', (SELECT COUNT(*) FROM stg_deliveries WHERE batter <> trim(batter))
UNION ALL SELECT 'deliveries: duplicate ball keys dropped', (SELECT COUNT(*) FROM stg_deliveries) - (SELECT COUNT(*) FROM cln_deliveries)
UNION ALL SELECT 'deliveries: super-over balls (excluded from player stats)', (SELECT SUM(super_over_flag) FROM cln_deliveries)
UNION ALL SELECT 'deliveries: wides + no-balls', (SELECT COUNT(*) FROM cln_deliveries WHERE legal_ball_flag = 0)
UNION ALL SELECT 'deliveries: runs outlier (>7 on a ball)', (SELECT SUM(dq_runs_outlier) FROM cln_deliveries)
UNION ALL SELECT 'deliveries: batsman+extra <> total', (SELECT SUM(dq_runs_mismatch) FROM cln_deliveries);

-- COMMAND ----------

CREATE OR REPLACE TABLE dq_assertions AS
WITH c AS (
  SELECT 'fact_matches.match_id unique' AS check_name, (SELECT COUNT(*) - COUNT(DISTINCT match_id) FROM fact_matches) AS failed_rows
  UNION ALL SELECT 'every clean match is in fact_matches', (SELECT COUNT(*) FROM cln_matches) - (SELECT COUNT(*) FROM fact_matches)
  UNION ALL SELECT 'every clean delivery is in fact_deliveries', (SELECT COUNT(*) FROM cln_deliveries) - (SELECT COUNT(*) FROM fact_deliveries)
  UNION ALL SELECT 'delivery key unique', (SELECT COUNT(*) FROM (SELECT match_id, inning, over_no, ball_no FROM fact_deliveries GROUP BY 1, 2, 3, 4 HAVING COUNT(*) > 1) x)
  UNION ALL SELECT 'winner is one of the two teams', (SELECT COUNT(*) FROM fact_matches WHERE winner_key IS NOT NULL AND winner_key NOT IN (team1_key, team2_key))
  UNION ALL SELECT 'toss winner is one of the two teams', (SELECT COUNT(*) FROM fact_matches WHERE toss_winner_key NOT IN (team1_key, team2_key))
  UNION ALL SELECT 'batting team <> bowling team', (SELECT COUNT(*) FROM fact_deliveries WHERE batting_team_key = bowling_team_key)
  UNION ALL SELECT 'over_no in 0..19', (SELECT COUNT(*) FROM fact_deliveries WHERE over_no NOT BETWEEN 0 AND 19)
  UNION ALL SELECT 'total_runs >= 0', (SELECT COUNT(*) FROM fact_deliveries WHERE total_runs < 0)
  UNION ALL SELECT 'every season has one champion', (SELECT COUNT(*) FROM dim_season WHERE champion IS NULL)
  UNION ALL SELECT 'runs reconcile: deliveries vs innings totals',
    (SELECT ABS((SELECT SUM(total_runs) FROM fact_deliveries WHERE inning IN (1, 2)) -
                (SELECT SUM(COALESCE(first_innings_runs, 0) + COALESCE(second_innings_runs, 0)) FROM fact_matches)))
)
SELECT check_name, failed_rows, CASE WHEN failed_rows = 0 THEN 'PASS' ELSE 'FAIL' END AS status FROM c;

-- COMMAND ----------

SELECT * FROM dq_row_counts ORDER BY entity;

-- COMMAND ----------

SELECT * FROM dq_assertions ORDER BY status, check_name;

-- COMMAND ----------

-- MAGIC %md
-- MAGIC ## Visual queries (same as the Lakeview dashboard)

-- COMMAND ----------

SELECT * FROM a_kpi_headline;

-- COMMAND ----------

-- Visualization: Win % by franchise (>= 40 matches) (hbar: x=team_name, y=win_pct)
SELECT team_name, win_pct FROM a_team_win_rates WHERE matches >= 40 ORDER BY win_pct DESC;

-- COMMAND ----------

-- Visualization: Average first-innings score by season (line: x=season, y=avg_first_innings_score)
SELECT season, avg_first_innings_score FROM a_season_trend ORDER BY season;

-- COMMAND ----------

-- Visualization: Toss winner win % by toss decision (bar: x=toss_decision, y=toss_winner_win_pct)
SELECT toss_decision, toss_winner_win_pct FROM a_toss_impact ORDER BY toss_decision;

-- COMMAND ----------

-- Visualization: Top 10 run scorers (hbar: x=batter, y=runs)
SELECT batter, runs FROM a_top_batters ORDER BY runs DESC LIMIT 10;

-- COMMAND ----------

-- Visualization: Top 10 wicket takers (hbar: x=bowler, y=wickets)
SELECT bowler, wickets FROM a_top_bowlers ORDER BY wickets DESC LIMIT 10;

-- COMMAND ----------

-- Visualization: Bat-first win % by venue (>= 20 matches) (hbar: x=venue, y=bat_first_win_pct)
SELECT venue, bat_first_win_pct FROM a_venue_effects ORDER BY matches DESC LIMIT 10;
